updated tf configuration and workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,14 +17,35 @@ jobs:
         with:
           role-to-assume: arn:aws:iam::736218978384:role/github-oidc-full-perms
           aws-region: ap-south-1
+      - name: install ssh_key_pair
+        run: ssh-keygen -t rsa -N "" -f "ec2keypair" 
       - name: initialize&format
+        id: init
         run: |
           terraform init
           terraform fmt
+        continue-on-error: true
       - name: plan_apply
+        id: plan
         run: terraform plan -out myplan
+        continue-on-error: true
+      - name: retry_plan #(run on failure)
+        if: steps.plan.outcome == 'failure'
+        run: |
+          echo "retrying plan.."
+          terraform plan -out myplan || terraform plan -out myplan
       - name: apply_plan
+        id: apply
         run: terraform apply myplan
+        continue-on-error: true
+      - name: Post-Deployment Outputs
+        if: always()
+        run: terraform output
+      - name: Failure Notification
+        if: failure()
+        run: |
+          echo "Terraform provisioning Failed!"
+          exit 1
   # deploy_website_using_ansible:
   #   runs-on: ubuntu-latest
   #   steps:
diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -2,7 +2,7 @@ name: destroy infra
 on: 
   workflow_dispatch:
 jobs:
-  create_infra:
+  destroy_infra:
     permissions:
       id-token: write
       contents: read
@@ -17,11 +17,34 @@ jobs:
         with:
           role-to-assume: arn:aws:iam::736218978384:role/github-oidc-full-perms
           aws-region: ap-south-1
+      - name: get key_name
+        run: ssh-keygen -t rsa -N "" -f "ec2keypair"
       - name: initialize
         run: terraform init
+        continue-on-error: true
+
       - name: plan_destroy
+        id: plan
         run: terraform plan -destroy -out myplan
+        continue-on-error: true
+
+      - name: retry_plan #(on failure)
+        if: steps.plan.outcome == 'failure'
+        run: |
+          echo "plan failed, retrying.."
+          terraform plan -destroy -out myplan || terraform plan -destroy -out myplan
+        continue-on-error: true
+
       - name: apply_destroy
         run: terraform apply myplan
+        continue-on-error: true
+      - name: Post-Deployment Outputs
+        if: always()
+        run: terraform output
+      - name: Failure Notification
+        if: failure()
+        run: |
+          echo "Terraform destroy Failed!"
+          exit 1
           
     
